fix kubeconfig

diff --git a/.github/workflows/reusable-deploy.yaml b/.github/workflows/reusable-deploy.yaml
--- a/.github/workflows/reusable-deploy.yaml
+++ b/.github/workflows/reusable-deploy.yaml
@@ -68,10 +68,14 @@ jobs:
 
       - name: Configure Kubeconfig & GPG
         run: |
-          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > "$HOME/.kube/config"
+          if [ -z "${{ secrets.KUBE_CONFIG }}" ]; then
+            echo "::error::Kubeconfig secret is empty. Please check the secret value in the environment settings."
+            exit 1
+          fi
+          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > "${{ runner.temp }}/kubeconfig"
           echo "${{ secrets.GPG_SECRET_KEY }}" | base64 --decode | gpg --batch --import
         env:
-          KUBECONFIG: "$HOME/.kube/config"
+          KUBECONFIG: "${{ runner.temp }}/kubeconfig"
 
       - name: Download Helm Chart & Checksum Artifact
         uses: actions/download-artifact@v4
@@ -81,10 +85,16 @@ jobs:
           run-id: ${{ inputs.run-id }}
           github-token: ${{ secrets.REPO_ACCESS_TOKEN }}
 
+      - name: Debugging Kubeconfig
+        run: |
+          echo "KUBECONFIG is set to: ${KUBECONFIG}"
+          echo "File content:"
+          cat "${KUBECONFIG}"
+
       - name: Generate Deployment Plan using release.py
         shell: bash
         env:
-          KUBECONFIG: "$HOME/.kube/config"
+          KUBECONFIG: "${{ runner.temp }}/kubeconfig"
         run: |
           CHART_PACKAGE=$(ls *.tgz)
           echo "Generating deployment plan using release.py..."
@@ -130,6 +140,10 @@ jobs:
 
       - name: Configure Kubeconfig & GPG
         run: |
+          if [ -z "${{ secrets.KUBE_CONFIG }}" ]; then
+            echo "::error::Kubeconfig secret is empty. Please check the secret value in the environment settings."
+            exit 1
+          fi
           echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > "$HOME/.kube/config"
           echo "${{ secrets.GPG_SECRET_KEY }}" | base64 --decode | gpg --batch --import
         env:
